### ISSUE TITLE
Still using short Unix style file names in home directory?

### ISSUE THREAD

**Issue by TRSx80** [budlabs/youtube#7]
Hi Bud!

I been enjoying your videos a lot, thanks for making and sharing them. :smile: 

One of your ideas I really liked was changing your home directory names to short 3-4 letter Unix style. I even went so far today as to start sketching out an outline of what that would look like for myself, when tweaked to my own needs / liking. But then I stopped because I had a thought / question.

Are you still doing it this way?

Because the thought occurred to me that this might get to eventually become a maintenance hassle? I have some time now, and am working on my setup, but some day that might not always be the case. Or maybe not. I dunno. I guess I need to think about it some more, before committing. Because that will be a pretty major (and potentially slightly breaking) change for a while.

I looked all over the Internet trying to find an email or something for you, without success. So I hope you don't mind me contacting you through here. :)

Cheers! :beers: 

TRS-80

**Comment by budRich** [comment]
hello TRS-80 , i am really sorry to reply this late.

Yes i do still use the same 3 letter names for the visible directories in ~ . I think i only done one re-install of my system in 3 years but setting this up takes no time at all. 

If i want to use the directories in scripts and such i do something like this:  

``` shell
musicdir=$(xdg-user-dir MUSIC)
if [[ -d $musicdir ]]; then
  echo "the full path to your music dir is $musicdir"
else
  echo "could not find music dir"
  exit 1
fi
```
Using that method you can be sure to get the correct path, no matter what they are named.

**Comment by TRSx80** [comment]
> i am really sorry to reply this late.

It's orite mate, I weren't dying from a heart attack!  :D

Hope all is well with you.

In the meantime I already been testing the waters, and I love it.  So thanks a lot for the idea!

Once I settle on a structure I like, I will make some short batch file to implement the finalized setup on a new machine, and put it with all my other dotfiles (I like to be able to completely provision a new box just by pulling down my dotfiles and running `make`).

Thanks for turning me on to `xdg-user-dir MUSIC` & etc., I had never heard of that before either.  But I sort of already realized by moving things around I broke some scripts which couldn't find things in certain places.  So I thought I would set some environmental variables pointing to certain directories, so I only need to set them once in `.profile` or whatever, and then change all my various scripts to use those values.  And this would be another option for that particular problem.

Cheers!  :beers:
